#!/usr/bin/env -S awk -f
BEGIN {
	FS="( bags contain |[.])"
}
{
	rules[$1] = $2
}
function find(needle, rule) {
	for (rule in rules) {
		if (index(rules[rule], needle) > 0) {
			++bags[rule]
			find(rule)
		}
	}
}
END {
	find("shiny gold")
	i = 0
	for (bag in bags) ++i
	print i
}
