#!/usr/bin/env -S awk -f
{
	cmd = substr($1, 1, 1)
	value = substr($1, 2)
	if (cmd == "N") {
		y -= value
	} else if (cmd == "E") {
		x += value
	} else if (cmd == "S") {
		y += value
	} else if (cmd == "W") {
		x -= value
	} else if (cmd == "L") {
		bearing = (bearing - value + 360) % 360
	} else if (cmd == "R") {
		bearing = (bearing + value) % 360
	} else if (cmd == "F") {
		if (bearing == 0) {
			x += value
		} else if (bearing == 90) {
			y += value
		} else if (bearing == 180) {
			x -= value
		} else if (bearing == 270) {
			y -= value
		}
	}
}
END {
	print x + y
}
