#!/usr/bin/env bash
report() {
	for D in *
	do
		[ -d "$D" ] && (
			cd "$D" || exit $?
			echo "## Day ${D#0}"
			for X in part*
			do
				echo -n "$X: "
				"./$X" input || exit $?
			done
			echo
		)
	done
}
check() {
	report | diff solutions -
}
save() {
	report > solutions
}
${@:-check}
