#!/usr/bin/env bash
for D in *
do
	[ -d "$D" ] && (
		cd "$D" || exit 1
		echo "-- $D. December 2020 -------------------"
		for X in part*
		do
			echo -n "$X: "
			"./$X" input || exit 1
		done
		echo
	)
done
