#!/usr/bin/env awk -f
END {
	FS = ""
	sum = 1
	split("1,1|3,1|5,1|7,1|1,2", steps, "|")
	for (step in steps) {
		split(steps[step], a, ",")
		right = a[1]
		down = a[2]
		trees = 0
		x = 0
		line = 0
		while ((getline < FILENAME) > 0) {
			++line
			if (down > 1 && line % down == 0) {
				continue
			}
			if ($(1 + x % NF) == "#") {
				++trees
			}
			x += right
		}
		close FILENAME
		sum *= trees
	}
	print sum
	exit
}
