#!/usr/bin/awk -f
BEGIN {
	FS=""
}
{
	max = 0
	for (i = 0; i < NF; ++i) {
		n = i + 1
		cup_values[i] = $n
		refs[i] = n
		lut[$n] = i
		if ($n > max) max = $n
	}
	ncups = NF
	ncups = 1000000
	n = max + 1
	for (; i < ncups; ++i) {
		cup_values[i] = n
		refs[i] = n
		lut[n] = i
		++n
	}
	refs[i - 1] = 0
	max = n - 1
	nrest = ncups - 4
	p = 0
	for (i = 0; i < 10000000; ++i) {
		dest = cup_values[p]
		first_pick = refs[p]
		nxt = first_pick
		for (j = 1; j <= 3; ++j) {
			last_pick = nxt
			nxt = refs[nxt]
		}
		while (1) {
			--dest
			if (dest < 1) dest = max
			check = first_pick
			found = 0
			for (j = 0; j < 3; ++j) {
				if (cup_values[check] == dest) {
					found = 1
					break
				}
				check = refs[check]
			}
			if (found == 0) break
		}
		insert = lut[dest]
		refs[p] = nxt
		after_insert = refs[insert]
		refs[insert] = first_pick
		refs[last_pick] = after_insert
		p = nxt
	}
	for (i = 0; i < ncups; ++i) {
		if (cup_values[i] == 1) {
			p = refs[i]
			first = cup_values[p]
			p = refs[p]
			second = cup_values[p]
			printf "%.0f\n", first * second
			break
		}
	}
}
