#!/usr/bin/env -S awk -f
BEGIN {
	plen = 25
}
function check(n, nr, a, b, base) {
	for (a = nr - plen; a <= nr; ++a) {
		base = preamble[a]
		for (b = a + 1; b <= nr; ++b) {
			if (base + preamble[b] == n) {
				return 1
			}
		}
	}
	return 0
}
{
	if (NR > plen) {
		if (check($1, NR - 1) == 0) {
			print $1
			exit
		}
	}
	preamble[NR] = $1
	if (NR > plen) {
		delete preamble[NR - plen]
	}
}
