#!/usr/bin/env -S awk -f
BEGIN {
	plen = 25
}
function check(n, nr, a, b, base) {
	for (a = nr - plen; a <= nr; ++a) {
		base = preamble[a]
		for (b = a + 1; b <= nr; ++b) {
			if (base + preamble[b] == n) {
				return 1
			}
		}
	}
	return 0
}
function find(target, len, min, max, a, b, base, n) {
	for (a = 1; a <= len; ++a) {
		min = 202073648049425
		max = 0
		base = list[a]
		for (b = a + 1; b <= len; ++b) {
			n = list[b]
			if (n < min) min = n
			if (n > max) max = n
			base += n
			if (base == target) {
				return min + max
			}
		}
	}
}
{
	if (NR > plen) {
		if (check($1, NR - 1) == 0) {
			print find($1, NR)
			exit
		}
	}
	preamble[NR] = $1
	list[NR] = $1
	if (NR > plen) {
		delete preamble[NR - plen]
	}
}
