#!/usr/bin/env -S awk -f
BEGIN {
	plen = 25
}
function check(n, a, b) {
	for (a in preamble) {
		for (b in preamble) {
			if (a != b && n == preamble[a] + preamble[b]) {
				return 1
			}
		}
	}
	return 0
}
{
	if (NR > plen) {
		if (check($1) == 0) {
			print $1
			exit
		}
	}
	preamble[NR] = $1
	if (NR > plen) {
		delete preamble[NR - plen]
	}
}
