#!/usr/bin/env awk -f
BEGIN {
	FS = ""
	min = 65535
}
{
	row_range = 127
	row = 0
	col_range = 7
	col = 0
	for (i = 0; i <= NF; ++i) {
		if ($i == "F") {
			row_range = int(row_range / 2)
		} else if ($i == "B") {
			row_range = int(row_range / 2)
			row += row_range + 1
		} else if ($i == "L") {
			col_range = int(col_range / 2)
		} else if ($i == "R") {
			col_range = int(col_range / 2)
			col += col_range + 1
		}
	}
	id = row * 8 + col
	if (id > max) {
		max = id
	}
	if (id < min) {
		min = id
	}
	ids[id] = 1
}
END {
	for (i = min; i <= max; ++i) {
		if (ids[i] != 1) {
			print i
			break
		}
	}
}
