#!/usr/bin/env -S awk -f
BEGIN {
	FS = ""
}
function decode(c, i) {
	return i * 2 + (c ~ /[BR]/ ? 1 : 0)
}
{
	row = 0
	col = 0
	for (i = 1; i <= NF; ++i) {
		if ($i ~ /[FB]/) {
			row = decode($i, row)
		} else if ($i ~ /[LR]/) {
			col = decode($i, col)
		}
	}
	id = row * 8 + col
	if (id > max) {
		max = id
	}
}
END {
	print max
}
