#!/usr/bin/env -S awk -f
BEGIN {
	FS = ""
	min = 65535
}
function decode(c, i) {
	return i * 2 + (c ~ /[BR]/ ? 1 : 0)
}
{
	row = 0
	col = 0
	for (i = 1; i <= NF; ++i) {
		if ($i ~ /[FB]/) {
			row = decode($i, row)
		} else if ($i ~ /[LR]/) {
			col = decode($i, col)
		}
	}
	id = row * 8 + col
	if (id > max) {
		max = id
	}
	if (id < min) {
		min = id
	}
	ids[id] = 1
}
END {
	for (i = min; i <= max; ++i) {
		if (ids[i] != 1) {
			print i
			break
		}
	}
}
