#!/usr/bin/env -S awk -f
BEGIN {
	RS = ""
}
{
	delete a
	for (i = 1; i <= NF; ++i) {
		for (j = length($i); j > 0; --j) {
			a[substr($i, j, 1)] += 1
		}
	}
	for (c in a) {
		if (a[c] == NF) {
			++count
		}
	}
}
END {
	print count
}
