#!/usr/bin/awk -f
{
	arr[NR] = $1
}
END {
	for (a in arr) {
		for (b in arr) {
			for (c in arr) {
				if (arr[a] + arr[b] + arr[c] == 2020) {
					print arr[a] * arr[b] * arr[c]
					exit
				}
			}
		}
	}
}
