#!/usr/bin/awk -f
{
	adapters[$1] = $1
	if ($1 > max) max = $1
}
END {
	len = 1
	for (i = 1; i <= max; ++i) {
		jolts = adapters[i]
		if (jolts < 1) continue
		sorted[len++] = jolts
	}
	options[0] = 1
	for (i = 1; i < len; ++i) {
		jolts = sorted[i]
		for (j = 1; j < 4; ++j) {
			k = options[jolts - j]
			if (k > 0) options[jolts] += k
		}
	}
	printf "%.0f\n", options[max]
}
