#!/usr/bin/awk -f
BEGIN {
	FS=","
}
{
	if (NF == 1) {
		t = $1
	} else {
		min = 999999
		for (i = 1; i <= NF; ++i) {
			if ($i == "x") continue
			wait = $i - (t % $i)
			if (wait < min) {
				min = wait
				line = $i
			}
		}
		print line * min
	}
}
