#!/usr/bin/awk -f
BEGIN {
	FS=","
}
{
	if (NF > 1) {
		last = 2
		step = $1
		for (t = 0; ; t += step) {
			miss = 0
			for (i = 2; i <= NF; ++i) {
				if ($i != "x" && (t + i - 1) % $i != 0) {
					if (i > last) {
						if (mark > 0) {
							step = t - mark
							mark = 0
							last = i
						} else {
							mark = t
						}
					}
					miss = 1
					break
				}
			}
			if (miss == 0) {
				printf "%.0f\n", t
				break
			}
		}
	}
}
