#!/usr/bin/awk -f
BEGIN {
	FS=","
	games = ENVIRON["GAMES"]
	games = games > 0 ? games : 2020
}
{
	delete spoken
	for (i = 1; i < NF; ++i) {
		spoken[$i] = i
	}
	last = $NF
	for (; i < games; ++i) {
		before = last
		s = spoken[last]
		last = i - (s > 0 ? s : i)
		spoken[before] = i
	}
	printf "%.0f\n", last
}
