#!/usr/bin/env awk -f
BEGIN {
	RS=""
	FS="[\n ]"
	split("byr|iyr|eyr|hgt|hcl|ecl|pid", req, "|")
}
{
	delete items
	items["byr"] = 0
	items["iyr"] = 0
	items["eyr"] = 0
	items["hgt"] = 0
	items["hcl"] = 0
	items["ecl"] = 0
	items["pid"] = 0
	for (i = 1; i <= NF; ++i) {
		split($i, a, /:/)
		++items[a[1]]
	}
	invalid = 0
	for (i in req) {
		if (items[req[i]] != 1) {
			invalid = 1
			break
		}
	}
	if (invalid == 0) {
		++valid
	}
}
END {
	print valid
}
